/**
 * Teams — Members sub-page audit.
 *
 * Source: landing-composer/src/pages/teams/members/Members.tsx
 * Mounts: prefabs/members/Members.tsx (Members prefab in scope="team")
 *
 * URL: /organizations/:orgId/teams/:teamId/members
 *
 * The page wires a Members prefab + AlertModal (id="delete-pending-team-member-modal").
 * Most interactive elements (members table rows, invite button, role popup,
 * remove confirmation actions) do not yet expose data-cy hooks; missing hooks
 * are tracked in /tmp/agent-handoff/new-tests-fe-followup.json.
 *
 * Each it() asserts exactly one outcome that mirrors its description verbatim.
 */

const API_URL = Cypress.env('API_URL');

const resolveFirstOrgId = (token) => {
  return cy
    .request({
      method: 'GET',
      url: `${API_URL}/fn-execute/organization`,
      headers: { Authorization: token},
      qs: { sort: JSON.stringify({ _id: -1 }) },
      failOnStatusCode: false,
    })
    .then((res) => {
      const list = Array.isArray(res.body) ? res.body : res.body?.data || [];
      const first = list.find((o) => !o?.deleted_at) || list[0];
      if (!first?._id) {
        throw new Error('[teams/members spec] resolveFirstOrgId: no organization on this account');
      }
      return first._id;
    });
};

const resolveOrCreateTeamId = (token, orgId) => {
  return cy
    .request({
      method: 'GET',
      url: `${API_URL}/fn-execute/organization/${orgId}/team`,
      headers: { Authorization: token},
      qs: { filter: JSON.stringify({ deleted_at: { $eq: null } }), sort: JSON.stringify({ _id: -1 }) },
      failOnStatusCode: false,
    })
    .then((res) => {
      const list = Array.isArray(res.body) ? res.body : res.body?.data || [];
      const first = list.find((t) => !t?.deleted_at) || list[0];
      if (first?._id) return first._id;

      const name = `cy-team-members-${Date.now()}`;
      return cy
        .request({
          method: 'POST',
          url: `${API_URL}/fn-execute/organization/${orgId}/team`,
          headers: { Authorization: token},
          body: { name, description: 'Cypress autogenerated team for members spec', organization: orgId },
          failOnStatusCode: false,
        })
        .then((createRes) => {
          const id = createRes.body?._id || createRes.body?.data?._id;
          if (!id) {
            throw new Error('[teams/members spec] resolveOrCreateTeamId: failed to create fallback team');
          }
          return id;
        });
    });
};

const seedTeamContext = () => {
  // cy.login() seeds cy.session() so editor pages bootstrap with the token
  // in localStorage. cy.getAuthToken() POSTs /login directly to obtain a
  // token usable by cy.request() — this is decoupled from window.localStorage
  // which is unreliable on cache-hit cy.session() restores (about:blank).
  cy.login();
  cy.getAuthToken().then((token) => {
    resolveFirstOrgId(token).then((orgId) => {
      cy.wrap(orgId).as('orgId');
      resolveOrCreateTeamId(token, orgId).then((teamId) => {
        cy.wrap(teamId).as('teamId');
      });
    });
  });
};

describe('Teams Members — page mount', () => {
  beforeEach(function () {
    seedTeamContext();
    cy.get('@teamId').then((teamId) => {
      cy.get('@orgId').then((orgId) => {
        cy.intercept('GET', `**/api/fn-execute/organization/${orgId}/team/${teamId}**`).as('getTeam');
        cy.visit(`/organizations/${orgId}/teams/${teamId}/members`);
        cy.wait('@getTeam', { timeout: 20000 });
      });
    });
  });

  it('should land on the /organizations/:orgId/teams/:teamId/members URL after navigation', function () {
    cy.location('pathname').should('eq', `/organizations/${this.orgId}/teams/${this.teamId}/members`);
  });

  it('should render the members prefab root so the team members body is mounted', () => {
    // ScopeView is the actual root of the prefab; spec accepts any of its
    // recognisable structural classes until a stable data-cy is added.
    cy.get(
      '[data-cy="members-prefab-root"], [class*="scopeView"], [class*="ScopeView"]',
      { timeout: 20000 }
    )
      .first()
      .should('exist');
  });

  it('should expose the invite member action so the page CTA is reachable', () => {
    // Fallback: locate any button whose label text matches the team-scope CTA
    // ("Invite member"). Will be replaced once data-cy="members-invite-btn" lands.
    cy.get('button', { timeout: 20000 })
      .filter((_, el) => /invite\s*member/i.test(el.innerText || ''))
      .first()
      .should('exist');
  });
});

describe('Teams Members — invite popup behavior', () => {
  beforeEach(function () {
    seedTeamContext();
    cy.get('@teamId').then((teamId) => {
      cy.get('@orgId').then((orgId) => {
        cy.visit(`/organizations/${orgId}/teams/${teamId}/members`);
      });
    });
    cy.get(
      '[data-cy="members-prefab-root"], [class*="scopeView"], [class*="ScopeView"]',
      { timeout: 20000 }
    )
      .first()
      .should('exist');
  });

  it('should open the invite-member-popup overlay when the Invite member CTA is invoked', () => {
    cy.get('button', { timeout: 15000 })
      .filter((_, el) => /invite\s*member/i.test(el.innerText || ''))
      .first()
      .should('not.be.disabled')
      .click({ force: true });
    cy.get('[id="invite-member-popup"]', { timeout: 10000 }).should('exist');
  });
});

describe('Teams Members — team load API contract', () => {
  beforeEach(function () {
    seedTeamContext();
    cy.get('@teamId').then((teamId) => {
      cy.get('@orgId').then((orgId) => {
        cy.intercept('GET', `**/api/fn-execute/organization/${orgId}/team/${teamId}**`).as('getTeam');
        cy.visit(`/organizations/${orgId}/teams/${teamId}/members`);
      });
    });
  });

  it('should fire a getTeam request scoped to the current team route', () => {
    cy.wait('@getTeam', { timeout: 20000 }).then((interception) => {
      expect(interception.response.statusCode).to.be.oneOf([200, 304]);
    });
  });

  it('should not respond with a 5xx from the getTeam endpoint', () => {
    cy.wait('@getTeam', { timeout: 20000 }).then((interception) => {
      const status = interception.response.statusCode;
      expect(status).to.be.lessThan(500);
    });
  });
});

describe('Teams Members — delete pending member modal mount', () => {
  beforeEach(function () {
    seedTeamContext();
    cy.get('@teamId').then((teamId) => {
      cy.get('@orgId').then((orgId) => {
        cy.visit(`/organizations/${orgId}/teams/${teamId}/members`);
      });
    });
    cy.get(
      '[data-cy="members-prefab-root"], [class*="scopeView"], [class*="ScopeView"]',
      { timeout: 20000 }
    )
      .first()
      .should('exist');
  });

  it('should keep the delete-pending-team-member-modal hidden by default on initial render', () => {
    // The AlertModal is conditionally mounted via OverlayPopup open prop.
    // Default state on first render is open=false → no DOM node.
    cy.get('[id="delete-pending-team-member-modal"]').should('not.exist');
  });
});

