/**
 * Teams — Overview sub-page audit.
 *
 * Source: landing-composer/src/pages/teams/overview/Overview.tsx
 * Mounts: prefabs/projects/Projects.tsx (ProjectsPrefab)
 *
 * URL: /organizations/:orgId/teams/:teamId/overview
 *
 * The overview body is the shared ProjectsPrefab — identical to the
 * organization overview, but scoped to a team. Most interactive elements
 * under Overview do not yet expose data-cy hooks; missing hooks are
 * tracked in /tmp/agent-handoff/new-tests-fe-followup.json.
 *
 * Each it() asserts exactly one outcome that mirrors its description verbatim.
 */

const API_URL = Cypress.env('API_URL');

/**
 * Resolves the first non-deleted organization id reachable by the current
 * test identity. Required because team routes are nested under an org.
 */
const resolveFirstOrgId = (token) => {
  return cy
    .request({
      method: 'GET',
      url: `${API_URL}/fn-execute/organization`,
      headers: { Authorization: token },
      qs: { sort: JSON.stringify({ _id: -1 }) },
      failOnStatusCode: false,
    })
    .then((res) => {
      const list = Array.isArray(res.body) ? res.body : res.body?.data || [];
      const first = list.find((o) => !o?.deleted_at) || list[0];
      if (!first?._id) {
        throw new Error('[teams/overview spec] resolveFirstOrgId: no organization on this account');
      }
      return first._id;
    });
};

/**
 * Resolves the first non-deleted team id under the given organization.
 * Creates an ephemeral team via the standard create endpoint if none exists
 * so the spec can run on a freshly seeded account.
 */
const resolveOrCreateTeamId = (token, orgId) => {
  return cy
    .request({
      method: 'GET',
      url: `${API_URL}/fn-execute/organization/${orgId}/team`,
      headers: { Authorization: token },
      qs: { filter: JSON.stringify({ deleted_at: { $eq: null } }), sort: JSON.stringify({ _id: -1 }) },
      failOnStatusCode: false,
    })
    .then((res) => {
      const list = Array.isArray(res.body) ? res.body : res.body?.data || [];
      const first = list.find((t) => !t?.deleted_at) || list[0];
      if (first?._id) return first._id;

      const name = `cy-team-overview-${Date.now()}`;
      return cy
        .request({
          method: 'POST',
          url: `${API_URL}/fn-execute/organization/${orgId}/team`,
          headers: { Authorization: token },
          body: { name, description: 'Cypress autogenerated team for overview spec', organization: orgId },
          failOnStatusCode: false,
        })
        .then((createRes) => {
          const id = createRes.body?._id || createRes.body?.data?._id;
          if (!id) {
            throw new Error('[teams/overview spec] resolveOrCreateTeamId: failed to create fallback team');
          }
          return id;
        });
    });
};

const seedTeamContext = () => {
  // cy.login() seeds cy.session() so editor pages bootstrap with the token
  // in localStorage. cy.getAuthToken() POSTs /login directly to obtain a
  // token usable by cy.request() — this is decoupled from window.localStorage
  // which is unreliable on cache-hit cy.session() restores (about:blank).
  cy.login();
  cy.getAuthToken().then((token) => {
    resolveFirstOrgId(token).then((orgId) => {
      cy.wrap(orgId).as('orgId');
      resolveOrCreateTeamId(token, orgId).then((teamId) => {
        cy.wrap(teamId).as('teamId');
      });
    });
  });
};

describe('Teams Overview — page mount', () => {
  beforeEach(function () {
    seedTeamContext();
    cy.get('@teamId').then((teamId) => {
      cy.get('@orgId').then((orgId) => {
        cy.intercept('GET', `**/api/fn-execute/organization/${orgId}/team/${teamId}**`).as('getTeam');
        cy.visit(`/organizations/${orgId}/teams/${teamId}/overview`);
        cy.wait('@getTeam', { timeout: 20000 });
      });
    });
  });

  it('should land on the /organizations/:orgId/teams/:teamId/overview URL after navigation', function () {
    cy.location('pathname').should('eq', `/organizations/${this.orgId}/teams/${this.teamId}/overview`);
  });

  it('should render the projects prefab dashboard container so the team overview body is mounted', () => {
    cy.get(
      '[data-cy="projects-prefab-root"], [class*="content"]',
      { timeout: 20000 }
    )
      .first()
      .should('exist');
  });

  it('should expose either the empty-projects message or a list of project cards once the loading skeleton disappears', () => {
    cy.get('[data-cy="empty-projects-message"], [class*="sites"]', { timeout: 25000 })
      .first()
      .should('exist');
  });
});

describe('Teams Overview — create project entry point', () => {
  beforeEach(function () {
    seedTeamContext();
    cy.get('@teamId').then((teamId) => {
      cy.get('@orgId').then((orgId) => {
        cy.visit(`/organizations/${orgId}/teams/${teamId}/overview`);
      });
    });
    cy.get(
      '[data-cy="empty-projects-message"], [class*="sites"], [class*="createNewButton"]',
      { timeout: 25000 }
    )
      .first()
      .should('exist');
  });

  it('should open the project-setup overlay when the New Website action is invoked', () => {
    // Fallback: no data-cy on the New Website button yet. The OverlayPopup id is stable.
    cy.get('[class*="createNewButton"]', { timeout: 15000 }).first().click({ force: true });
    cy.get('[id="project-setup"]', { timeout: 10000 }).should('exist');
  });
});

describe('Teams Overview — projects API contract', () => {
  beforeEach(function () {
    seedTeamContext();
    cy.get('@teamId').then((teamId) => {
      cy.get('@orgId').then((orgId) => {
        cy.intercept('GET', '**/api/fn-execute/project**').as('getProjects');
        cy.visit(`/organizations/${orgId}/teams/${teamId}/overview`);
      });
    });
  });

  it('should fire a getProjects request scoped to the current team overview', () => {
    cy.wait('@getProjects', { timeout: 20000 }).then((interception) => {
      expect(interception.response.statusCode).to.be.oneOf([200, 304]);
    });
  });

  it('should not respond with a 5xx from the projects endpoint', () => {
    cy.wait('@getProjects', { timeout: 20000 }).then((interception) => {
      const status = interception.response.statusCode;
      expect(status).to.be.lessThan(500);
    });
  });
});

