/**
 * Teams — Settings sub-page audit.
 *
 * Source: landing-composer/src/pages/teams/settings/Settings.tsx
 * Mounts: atoms/Input/Input + atoms/button/Button (no prefab).
 *
 * URL: /organizations/:orgId/teams/:teamId/settings
 *
 * The page renders, once the team payload arrives, two inputs ("Team Name",
 * "Team Description") and two buttons ("Update Profile" primary, "Delete Team"
 * danger). None expose data-cy hooks today; missing hooks are tracked in
 * /tmp/agent-handoff/new-tests-fe-followup.json.
 *
 * Each it() asserts exactly one outcome that mirrors its description verbatim.
 */

const API_URL = Cypress.env('API_URL');

const resolveFirstOrgId = (token) => {
  return cy
    .request({
      method: 'GET',
      url: `${API_URL}/fn-execute/organization`,
      headers: { Authorization: token },
      qs: { sort: JSON.stringify({ _id: -1 }) },
      failOnStatusCode: false,
    })
    .then((res) => {
      const list = Array.isArray(res.body) ? res.body : res.body?.data || [];
      const first = list.find((o) => !o?.deleted_at) || list[0];
      if (!first?._id) {
        throw new Error('[teams/settings spec] resolveFirstOrgId: no organization on this account');
      }
      return first._id;
    });
};

const resolveOrCreateTeamId = (token, orgId) => {
  return cy
    .request({
      method: 'GET',
      url: `${API_URL}/fn-execute/organization/${orgId}/team`,
      headers: { Authorization: token },
      qs: { filter: JSON.stringify({ deleted_at: { $eq: null } }), sort: JSON.stringify({ _id: -1 }) },
      failOnStatusCode: false,
    })
    .then((res) => {
      const list = Array.isArray(res.body) ? res.body : res.body?.data || [];
      const first = list.find((t) => !t?.deleted_at) || list[0];
      if (first?._id) return first._id;

      const name = `cy-team-settings-${Date.now()}`;
      return cy
        .request({
          method: 'POST',
          url: `${API_URL}/fn-execute/organization/${orgId}/team`,
          headers: { Authorization: token },
          body: { name, description: 'Cypress autogenerated team for settings spec', organization: orgId },
          failOnStatusCode: false,
        })
        .then((createRes) => {
          const id = createRes.body?._id || createRes.body?.data?._id;
          if (!id) {
            throw new Error('[teams/settings spec] resolveOrCreateTeamId: failed to create fallback team');
          }
          return id;
        });
    });
};

const seedTeamContext = () => {
  // cy.login() seeds cy.session() so editor pages bootstrap with the token
  // in localStorage. cy.getAuthToken() POSTs /login directly to obtain a
  // token usable by cy.request() — this is decoupled from window.localStorage
  // which is unreliable on cache-hit cy.session() restores (about:blank).
  cy.login();
  cy.getAuthToken().then((token) => {
    resolveFirstOrgId(token).then((orgId) => {
      cy.wrap(orgId).as('orgId');
      resolveOrCreateTeamId(token, orgId).then((teamId) => {
        cy.wrap(teamId).as('teamId');
      });
    });
  });
};

describe('Teams Settings — page mount', () => {
  beforeEach(function () {
    seedTeamContext();
    cy.get('@teamId').then((teamId) => {
      cy.get('@orgId').then((orgId) => {
        cy.intercept('GET', `**/api/fn-execute/organization/${orgId}/team/${teamId}**`).as('getTeam');
        cy.visit(`/organizations/${orgId}/teams/${teamId}/settings`);
        cy.wait('@getTeam', { timeout: 20000 });
      });
    });
  });

  it('should land on the /organizations/:orgId/teams/:teamId/settings URL after navigation', function () {
    cy.location('pathname').should('eq', `/organizations/${this.orgId}/teams/${this.teamId}/settings`);
  });

  it('should render the Team Name input once the team payload resolves', () => {
    cy.get('input[placeholder="Team Name"]', { timeout: 20000 }).should('exist');
  });

  it('should render the Team Description input once the team payload resolves', () => {
    cy.get('input[placeholder="Team Description"]', { timeout: 20000 }).should('exist');
  });

  it('should render both the Update Profile and Delete Team buttons in the settings form', () => {
    cy.get('button', { timeout: 20000 })
      .filter((_, el) => /update\s*profile/i.test(el.innerText || ''))
      .should('have.length.at.least', 1);
    cy.get('button')
      .filter((_, el) => /delete\s*team/i.test(el.innerText || ''))
      .should('have.length.at.least', 1);
  });
});

describe('Teams Settings — form interactions', () => {
  beforeEach(function () {
    seedTeamContext();
    cy.get('@teamId').then((teamId) => {
      cy.get('@orgId').then((orgId) => {
        cy.intercept('GET', `**/api/fn-execute/organization/${orgId}/team/${teamId}**`).as('getTeam');
        cy.visit(`/organizations/${orgId}/teams/${teamId}/settings`);
        cy.wait('@getTeam', { timeout: 20000 });
      });
    });
    cy.get('input[placeholder="Team Name"]', { timeout: 20000 }).should('exist');
  });

  it('should reflect a new value in the Team Name input when the user types into it', () => {
    const sample = `Renamed ${Date.now()}`;
    cy.get('input[placeholder="Team Name"]').clear({ force: true }).type(sample, { delay: 0 });
    cy.get('input[placeholder="Team Name"]').should('have.value', sample);
  });

  it('should reflect a new value in the Team Description input when the user types into it', () => {
    const sample = `Cypress description ${Date.now()}`;
    cy.get('input[placeholder="Team Description"]').clear({ force: true }).type(sample, { delay: 0 });
    cy.get('input[placeholder="Team Description"]').should('have.value', sample);
  });

  it('should send a PATCH /team/:id/profile request when the Update Profile button is clicked', function () {
    cy.intercept('PATCH', `**/api/fn-execute/organization/${this.orgId}/team/${this.teamId}/profile**`).as('updateTeam');
    cy.get('button')
      .filter((_, el) => /update\s*profile/i.test(el.innerText || ''))
      .first()
      .click({ force: true });
    cy.wait('@updateTeam', { timeout: 20000 }).then((interception) => {
      const status = interception.response?.statusCode ?? 0;
      expect(status, 'PATCH /profile status').to.be.lessThan(500);
    });
  });
});

describe('Teams Settings — team load API contract', () => {
  beforeEach(function () {
    seedTeamContext();
    cy.get('@teamId').then((teamId) => {
      cy.get('@orgId').then((orgId) => {
        cy.intercept('GET', `**/api/fn-execute/organization/${orgId}/team/${teamId}**`).as('getTeam');
        cy.visit(`/organizations/${orgId}/teams/${teamId}/settings`);
      });
    });
  });

  it('should fire a getTeam request scoped to the current team route on mount', () => {
    cy.wait('@getTeam', { timeout: 20000 }).then((interception) => {
      expect(interception.response.statusCode).to.be.oneOf([200, 304]);
    });
  });

  it('should not respond with a 5xx from the getTeam endpoint', () => {
    cy.wait('@getTeam', { timeout: 20000 }).then((interception) => {
      const status = interception.response.statusCode;
      expect(status).to.be.lessThan(500);
    });
  });
});

