/**
 * Regression tests for the scopeToPlayground() CSS injection bug.
 *
 * Bug fixed: scopeToPlayground() used the regex [^{]*? which could cross line
 * boundaries. When CSS had multi-line rule blocks (e.g. override styles for h1–h6
 * generated by Quick Save), the regex treated CSS property lines as selectors and
 * prepended "#playground" inside rule bodies, producing:
 *
 *   .Component_v1_h1 {
 *     #playground color: var(--composer-font-color-primary);  ← invalid
 *   }
 *
 * Browsers silently discard invalid declarations, so the color never applied.
 *
 * Fix: changed [^{]*? → [^{\n]*? (excludes newlines from the capture group).
 * All selectors on their own line are correctly scoped; property lines are left untouched.
 */

import { loginToEditor } from '@support/editorTestHelper';

const PROJECT_ID = Cypress.env('TEST_PROJECT_ID') || '69f515295ac7bd7572f9590c';
const EDITOR_URL = `/project/${PROJECT_ID}/editor/0`;

const COMPONENT_NAME = 'CssScoping Test';
const COMPONENT_SAFE_NAME = 'CssScopingTest';
const VERSION = 1;

// Styles containing multi-line CSS rules with color declarations on their own lines.
// This is the exact pattern that triggered the bug in the original regex.
const MOCK_STYLES_CONTENT = `
.${COMPONENT_SAFE_NAME}_v${VERSION}_container .${COMPONENT_SAFE_NAME}_v${VERSION}_content .${COMPONENT_SAFE_NAME}_v${VERSION}_h1 {
  color: var(--composer-font-color-primary);
}

.${COMPONENT_SAFE_NAME}_v${VERSION}_container .${COMPONENT_SAFE_NAME}_v${VERSION}_content .${COMPONENT_SAFE_NAME}_v${VERSION}_h2 {
  color: var(--composer-font-color-primary);
}

.${COMPONENT_SAFE_NAME}_v${VERSION}_container .${COMPONENT_SAFE_NAME}_v${VERSION}_content .${COMPONENT_SAFE_NAME}_v${VERSION}_h3 {
  color: var(--composer-font-color-primary);
}
`.trim();

const MOCK_BUNDLE_CONTENT = `
window.__CUSTOM_COMPONENTS__["${COMPONENT_SAFE_NAME}_v${VERSION}"] = class ${COMPONENT_SAFE_NAME} {
  static getName() { return "${COMPONENT_NAME}"; }
  static getVersion() { return ${VERSION}; }
  render() { return null; }
  static getExportedCSSClasses() { return {}; }
};
`.trim();

describe('scopeToPlayground — CSS injection scoping regression', () => {
  beforeEach(() => {
    loginToEditor();

    cy.intercept('GET', `**/v1/projects/${PROJECT_ID}/custom-components*`, {
      body: [
        {
          _id: 'css-scope-test-id',
          name: COMPONENT_NAME,
          category: 'custom',
          version: VERSION,
          bundle_url: '',
          bundle_content: MOCK_BUNDLE_CONTENT,
          styles_url: '',
          styles_content: MOCK_STYLES_CONTENT,
          status: 'active',
          props_schema: '[]',
        },
      ],
    }).as('getCustomComponents');
  });

  it('injects scoped CSS without corrupting rule bodies (no #playground inside declarations)', () => {
    cy.visit(EDITOR_URL);
    cy.wait('@getCustomComponents');

    // Wait for the playground to render
    cy.get('#playground').should('exist');

    cy.window().then((win) => {
      const styleElements = Array.from(win.document.querySelectorAll('style'));
      const componentStyle = styleElements.find(
        (s) => s.textContent && s.textContent.includes(`${COMPONENT_SAFE_NAME}_v${VERSION}`)
      );

      // The style element must exist (component styles were injected)
      expect(componentStyle, 'Component style element should be injected').to.exist;

      const css = componentStyle.textContent;

      // REGRESSION CHECK: "#playground" must NOT appear at the start of a property
      // declaration line (i.e. prefixed by whitespace and followed by a CSS property).
      // Original bug produced lines like:  "  #playground color: var(...);"
      expect(css).not.to.match(/^\s+#playground\s+[a-z-]+\s*:/m);

      // All three selectors must be correctly scoped with #playground
      expect(css).to.contain(`#playground .${COMPONENT_SAFE_NAME}_v${VERSION}_container`);

      // The color declarations must still be present and valid
      expect(css).to.contain('color: var(--composer-font-color-primary)');
    });
  });

  it('scopes all h1–h3 selectors while preserving their color declarations', () => {
    cy.visit(EDITOR_URL);
    cy.wait('@getCustomComponents');

    cy.get('#playground').should('exist');

    cy.window().then((win) => {
      const sheets = Array.from(win.document.styleSheets);
      const matchedRules = [];

      for (const sheet of sheets) {
        try {
          const rules = Array.from(sheet.cssRules || []);
          for (const rule of rules) {
            if (rule.selectorText && rule.selectorText.includes(`${COMPONENT_SAFE_NAME}_v${VERSION}`)) {
              matchedRules.push({
                selector: rule.selectorText,
                color: rule.style && rule.style.color,
              });
            }
          }
        } catch (_) {
          // cross-origin sheets — skip
        }
      }

      // There should be 3 rules (h1, h2, h3)
      expect(matchedRules.length).to.equal(3);

      // Every rule must:
      // 1. Have a selector starting with #playground
      // 2. Have a color value (not empty — means it was correctly parsed by the browser)
      for (const { selector, color } of matchedRules) {
        expect(selector).to.match(/^#playground /);
        expect(color).not.to.equal('');
      }
    });
  });
});
